import Link from 'next/link';
import type {SalesReport} from '@/modules/sales/types';
import {money,percentage} from '@/modules/sales/validation';
export function ReportView({report,workspace,compact=false}:{report:SalesReport;workspace:string;compact?:boolean}){
 const cards=[['Leads created',report.leads.created],['Leads worked',report.leads.worked],['Meetings set',report.outcomes.SET??0],['Confirmed',report.outcomes.CONFIRM??0],['Shows',report.outcomes.SHOW??0],['No-shows',report.outcomes.NO_SHOW??0],['Won',report.outcomes.CLOSE_WON??0],['Lost',report.outcomes.CLOSE_LOST??0],['Nurtures',report.outcomes.NURTURE??0],['Follow-up / decision',report.outcomes.FOLLOW_UP??0],['Tasks completed',report.tasks.completed],['Overdue tasks',report.tasks.overdue],['Outstanding actions',report.tasks.outstanding]];
 return <div className="space-y-5"><p className="text-xs text-slate-500">{report.from} – {report.to} · {report.timezone}. Outcome counts use event dates. Live tasks and stages show the current position; saved EOD task counts use the selected day’s cutoff.</p><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{cards.map(([label,n])=><div key={label} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{n}</p></div>)}</div><div className="grid gap-3 md:grid-cols-3">{report.currencies.map(c=><article key={c.currency} className="rounded-xl border border-emerald-100 bg-emerald-50 p-4"><h3 className="font-semibold">{c.currency}</h3><p className="mt-2 text-sm">Deal value: {money(c.deal_value_minor,c.currency)}</p><p className="mt-1 text-sm">Net cash: {money(c.cash_minor,c.currency)}</p></article>)}</div>{report.currencies.length===0&&<p className="text-sm text-slate-500">No sales value or cash entries in this period.</p>}
 {!compact&&<><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Conversion definitions</h2><p className="mt-2 text-sm">Show rate: {percentage(report.denominators.attendance_showed,report.denominators.attendance_resolved)} ({report.denominators.attendance_showed} showed / {report.denominators.attendance_resolved} resolved attendance). Cohort: meetings scheduled in the date range; pending and cancelled bookings excluded.</p><p className="mt-2 text-sm">Win rate: {percentage(report.denominators.closed_won,report.denominators.closed_decisions)} ({report.denominators.closed_won} won / {report.denominators.closed_decisions} won-or-lost outcomes in range). A zero denominator displays —.</p></div><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Historical rep performance</h2><p className="mt-1 text-xs text-slate-500">Setter and closer dimensions overlap. Never sum them into a workspace total.</p><ul className="mt-3 space-y-2 text-sm">{report.performance.map((p,i)=><li key={i}>{p.credit_role} · {p.membership_id.slice(0,8)} · {p.action.replaceAll('_',' ')}: {p.count}</li>)}</ul></div><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Outcome evidence</h2><p className="mt-1 text-xs text-slate-500">Up to 100 events per page. Historical credit remains counted when current lead access has changed.</p><ul className="mt-3 divide-y divide-slate-100">{report.drilldown.map(d=><li key={d.activity_id} className="flex items-center justify-between gap-3 py-3 text-sm"><span>{d.action.replaceAll('_',' ')} · {new Date(d.at).toLocaleDateString('en',{timeZone:report.timezone})}</span>{d.lead_id?<Link className="font-medium text-[#116c58] hover:underline" href={`/${workspace}/leads/${d.lead_id}`}>View lead →</Link>:<span className="text-xs text-slate-500">Lead access restricted</span>}</li>)}</ul></div></>}
 </div>;
}
